apiVersion: v2
name: spectraplot
description: A Helm chart for deploying spectraplot to Kubenetes

# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
type: application

# Chart Version
version: 0.1.0

appVersion: "1.16.0"
